### ISSUE TITLE
check_memory_by_ssh improperly handles swap of size zero (0)

### ISSUE THREAD

**Issue by narunask** [naparuba/check-linux-by-ssh#38] opened 2015-11-05 15:26 UTC
On my VPS I don't have `swap` enabled and this leads to the division by zero condition on line `159` in the `check_memory_by_ssh improperly.py`.

I solved it with the following changes:

        try:
            perfdata += ' %s=%s%%;;;0%%;100%%' % (k, int(100 * float(v)/swap_total))
        except ZeroDivisionError:
            perfdata += ' %s=%s%%;;;0%%;100%%' % (k, int(100 * float(v)/1))

Not sure if that's the right way to do it so please update your master.

**Comment by david-guenault** [comment] 2016-02-03 18:00
Confirmed here ! Can you submit a PR (patch) ?

**Comment by narunask** [comment] 2016-02-04 10:15
It seems I cannot `push` to your repo, so here's patch.
    
    diff --git a/check_memory_by_ssh.py b/check_memory_by_ssh.py
    index 6e5cce9..ca42e61 100755
    --- a/check_memory_by_ssh.py
    +++ b/check_memory_by_ssh.py
    @@ -156,7 +156,10 @@ if __name__ == '__main__':
         if opts.swap :
             d_swap = {'swap_used':swap_used, 'swap_free':swap_free}
             for (k,v) in d_swap.iteritems():
    -            perfdata += ' %s=%s%%;;;0%%;100%%' % (k, int(100 * float(v)/swap_total))
    +            try:
    +                perfdata += ' %s=%s%%;;;0%%;100%%' % (k, int(100 * float(v)/swap_total))
    +            except ZeroDivisionError:
    +                perfdata += ' %s=%s%%;;;0%%;100%%' % (k, int(100 * float(v)/1))

**Comment by david-guenault** [comment] 2016-03-05 06:13
you don't have to push to the repo
clone the repo, modify the code and the submit PR

thx ;-)

**Comment by narunask** [comment] 2016-03-17 12:56
@david-guenault Please have review #45 :smile:

**Comment by david-guenault** [comment] 2016-05-03 09:35
mmh this is a duplicate of #40 and i will merge the first pr. sorry for the delay was waiting from naparuba aproval. I close this one

**Closed by david-guenault** 2016-05-03 09:35 UTC
Labels: bug
